name: Check PR Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [1.43.6]

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Deno format check
        run: deno fmt --check
      - name: Deno lint check
        run: deno task lint
      - name: Test Deno Module
        run: deno task test
